version = 5.6.0
archive_dir = /etc/letsencrypt/archive/weddingnadiabagus.my.id
cert = /etc/letsencrypt/live/weddingnadiabagus.my.id/cert.pem
privkey = /etc/letsencrypt/live/weddingnadiabagus.my.id/privkey.pem
chain = /etc/letsencrypt/live/weddingnadiabagus.my.id/chain.pem
fullchain = /etc/letsencrypt/live/weddingnadiabagus.my.id/fullchain.pem
[renewalparams]
account = 7c2fad799ee73013bfa5b359659ed02f
authenticator = standalone
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
