services:
    app:
        build:
            context: ../api-undangan
            dockerfile: docker/php/Dockerfile
        container_name: undangan-app
        depends_on:
            - db
        networks:
            - undangan

    db:
        image: postgres:16
        container_name: undangan-db
        environment:
            POSTGRES_DB: undangan
            POSTGRES_USER: root
            POSTGRES_PASSWORD: 12345678
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - undangan

    pgadmin:
        image: dpage/pgadmin4
        container_name: undangan-pgadmin
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
        networks:
            - undangan
        depends_on:
            - db

    frontend:
        image: node:20-alpine
        container_name: undangan-frontend
        working_dir: /app
        volumes:
            - .:/app:Z                           # ← folder undangan (frontend)
            - ../api-undangan/public:/app/public:Z  # ← hasil build ke public API
        command: sh -c "npm install && npm run build:public"
        networks:
            - undangan

    nginx:
        build:
            context: ../api-undangan
            dockerfile: docker/nginx/Dockerfile
        container_name: undangan-nginx
        ports:
            - "8080:80"
        depends_on:
            - app
            - frontend
        networks:
            - undangan
        volumes:
            - ../api-undangan/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:Z
            - ../api-undangan:/var/www:Z

volumes:
    postgres_data:

networks:
    undangan:
        driver: bridge